// add to cart
export const ADD_TOCART_LOAD = "ADD_TOCARTTLOAD";
export const ADD_TOCART_SUCCESS = "ADD_TOCARTTSUCCESS";
export const ADD_TOCART_FAIL = "ADD_TOCARTTFAIL";

//remove
export const REMOVE_FROMCART_LOAD = "REMOVE_FROMCART_LOAD";
export const REMOVE_FROMCART_SUCCESS = "REMOVE_FROMCART_SUCCESS";
export const REMOVE_FROMCART_FAIL = "REMOVE_FROMCART_FAIL";

//clear
export const CLEAR_CART_LOAD = "CLEAR_CART_LOAD";
export const CLEAR_CART_SUCCESS = "CLEAR_CART_SUCCESS";
export const CLEAR_CART_FAIL = "CLEAR_CART_FAIL";