export const GET_PRODUCT_LOAD = "GET_PRODUCT_LOAD";
export const GET_PRODUCT_SUCCESS = "GET_PRODUCT_SUCCESS";
export const GET_PRODUCT_FAIL = "GET_PRODUCT_FAIL";


export const GET_PRODUCTBYID_LOAD = "GET_PRODUCTBYID_LOAD";
export const GET_PRODUCTBYID_SUCCESS = "GET_PRODUCTBYID_SUCCESS";
export const GET_PRODUCTBYID_FAIL = "GET_PRODUCTBYID_FAIL";

export const DELETE_PRODUCTBYID_LOAD = "DELETE_PRODUCTBYID_LOAD";
export const DELETE_PRODUCTBYID_SUCCESS = "DELETE_PRODUCTBYID_SUCCESS";
export const DELETE_PRODUCTBYID_FAIL = "DELETE_PRODUCTBYID_FAIL";

export const ADD_PRODUCT_LOAD = "ADD_PRODUCT_LOAD";

export const ADD_PRODUCT_SUCCESS = "ADD_PRODUCT_SUCCESS";
export const ADD_PRODUCT_FAIL = "ADD_PRODUCT_FAIL";

export const EDIT_PRODUCT_LOAD = "EDIT_PRODUCT_LOAD";
export const EDIT_PRODUCT_SUCCESS = "EDIT_PRODUCT_SUCCESS";
export const EDIT_PRODUCT_FAIL = "EDIT_PRODUCT_FAIL";


export const CLEAR_SUCCESS_PRODUCT = "CLEAR_SUCCESS_PRODUCT";
export const CLEAR_ERRORS_PRODUCT = "CLEAR_ERRORS_PRODUCT";